{% set name = "jwcrypto" %}
{% set version = "1.0" %}
{% set sha256 = "f88816eb0a41b8f006af978ced5f171f33782525006cdb055b536a40f4d46ac9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python !=3.9.5
    - pip
  run:
    - python !=3.9.5
    - cryptography >=1.5

test:
  imports:
    - jwcrypto

about:
  home: https://jwcrypto.readthedocs.io/en/latest/
  license: LGPL v3.0
  license_family: LGPL
  license_file: LICENSE
  summary: Implements JWK,JWS,JWE specifications using python-cryptography
  doc_url: https://jwcrypto.readthedocs.io/en/latest/
  dev_url: https://github.com/latchset/jwcrypto
