{% set name = "jwcrypto" %}
{% set version = "0.8" %}
{% set sha256 = "b7fee2635bbefdf145399392f5be26ad54161c8271c66b5fe107b4b452f06c24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cryptography >=1.5

test:
  imports:
    - jwcrypto

about:
  home: https://jwcrypto.readthedocs.io/en/latest/
  license: LGPL v3.0
  license_family: LGPL
  license_file: LICENSE
  summary: Implements JWK,JWS,JWE specifications using python-cryptography
  doc_url: https://jwcrypto.readthedocs.io/en/latest/
  dev_url: https://github.com/latchset/jwcrypto
